FROM python:3.13-slim as builder

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    libglib2.0-0 libsm6 libxrender1 libxext6 \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY app/requirements.txt .

RUN pip install --no-cache-dir --target=/python-deps -r requirements.txt

FROM python:3.13-slim

WORKDIR /app

COPY --from=builder /python-deps /usr/local/lib/python3.11/site-packages/

COPY app/ /app/
COPY model/ /app/model/

ENTRYPOINT ["python", "inference.py"]
